### ISSUE TITLE
空调品牌列表中没有找到『奥克斯』

### ISSUE THREAD

**Issue by Caffreyfans** [irext/irext#10]
根据 ”https://irext.net/irext-server/indexing/list_brands“ 获取空调品牌，发现列表中缺少『奥克斯』

**Comment by strawmanbobi** [comment]
由于 aux 在空调的 brand 当中位列第一，所以请注意 from 参数填 0 而并非填 1。
https://irext.net/irext-server/indexing/list_brands
{id:'x',token:'xxxxx',categoryId:'1'**,from:'0',**count:'10'}
