### ISSUE TITLE
部署本地控制台问题

### ISSUE THREAD

**Issue by TanJunYi** [irext/irext#11]
IRext 文档
部署本地控制台
第四步：data/db/irext_xxxxx.sql 应该是database/db/irext_xxxxx.sql 
执行到第八步“运行工程根目录下的 ./run.sh，启动控制台服务”找不到run.sh文件
安装private-console工程下步骤执行也没有找到script_run.sh文件

**Comment by strawmanbobi** [comment]
Fixed
