### ISSUE TITLE
部分码库解析导致崩溃

### ISSUE THREAD

**Issue by tianbl** [irext/irext#12]
你好，部分码库解析发生错误，比如remoteIndexId=3521的码库解析会发生如下错误，直接导致jvm崩溃
2019-06-13 13:58:20.884  INFO 72566 --- [nio-8089-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 12 ms
loading decode library /data/irext/libirda_decoder.so
[IRDecode] AC Status = 1, 0, 4, 0, 0, keyCode = 0
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f57ec8d07b4, pid=72566, tid=0x00007f57edae9700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_92-b14) (build 1.8.0_92-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.92-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libirda_decoder.so+0x47b4]  apply_ac_parameter_type_1+0xaf
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/eastsoft/jiangxi/irext/hs_err_pid72566.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
eastsoft@ubuntu:~/jiangxi/irext$ java -jar irext-decode-service-0.2.0.jar 
SLF4J: Class path contains multiple SLF4J bindings.

**Comment by strawmanbobi** [comment]
请升级到最新的 0.2.1 版本，配合最新文档。此问题解决。
