### ISSUE TITLE
如何特定的查找指定的id？

### ISSUE THREAD

**Issue by lujiawei922** [irext/irext#13]
作者你好，我看了下你的文档，了解了下大概的过程，是这样子理解的。通过电器种类和品牌，能够查询到一个remote_list的表，但不能具体到一个指定的唯一ID，有什么更好的方法能够识别到指定的ID吗？

**Comment by strawmanbobi** [comment]
你好，ID 是指这个 remote_index 对象中的 id 字段，可以通过 remoteIndex.getId(); 来得到 （Java example）
但是我相信你提这个 issue 应该是有别的诉求，请说明你的诉求。

**Comment by lujiawei922** [comment]
我是想着纯c语言中中做离线查找操作，比如我如何在离线的情况下找到一个对应的电器的唯一指定ID，我现在的想法是根据品牌和类型在sqlite数据库中查找到符合的一列表，然后在列表中依次遍历匹配电器
的红外线操作，就像市场上的那些万能遥控器。有啥方法能在离线的情况下不用遍历直接找到电器对应的id，期望得到你的答复

**Comment by strawmanbobi** [comment]
remote_index 是一个根据品牌或者城市（对于机顶盒而言）下的列表，目前市面上所有的红外遥控产品都只能返回这么一个列表。用户得到列表之后需要用红外产品（比如APP）对着自己家的电器发射一下亲自尝试，逐个匹配。
如果按键发射之后电器有响应，比如电视机打开，能调音量等。那么就保存下来作为日常使用。如果遍历所有的 remote_index 之后都找不到一款是能够正常控制的，那就说明码库里没有，不支持这款家电。
能用到的优化策略有二：
1. 目前 IRext 的码库是根据市面上的电器产品排过序的，会把最普遍的，常用的放在每个 remote_index 的前面，优先级依次降低（也就是 remote_index.priority，越小表示越优先），这样提高匹配效率。
2. 做产品开发的时候可以选择几个典型的按键，比如电视机的电源、音量、静音作为关键匹配按键，如果三个都能正常控制，那么很大概率这个遥控码就是最终用户想要的码（但不尽然）。

**Comment by lujiawei922** [comment]
好的，十分感谢你的解答。我会根据品牌和类型挑选出一部分，然后在挑选出来的列表当中逐个遍历。
