### ISSUE TITLE
【空调一键匹配】

### ISSUE THREAD

**Issue by Joketinnle** [irext/irext#14]
Hi strawmanbobi
   我正在用ESP8266做一个红外控制器，其中一个项目要求是添加空调红外一键匹配功能。
参考其他产品，进入红外匹配模式，对着设备按空调开机键，就可以根据其接收到的红外编码进行正确的匹配。P.S. 我是写FW的。
  我现在从您那里了解到的空调红外编码方式是，每发送一次红外讯号，其一帧数据包含了空调的所有讯息。模式，风速，风向，POWER ON/OFF，等等. 但是每个空调厂商其不同型号的空调编码方式也有不同。我试图从您写的解码程序入手，查找空调是否一个相对好判断的特征。但是可惜的是"我好像没看懂😄😄"（只能大致了解  感觉这种方式并不可行 ）。
  所以我现在的解决方案是这样的：
  **方案一：** 
    对接收到的空调红外讯号的前9Bit(前18个高低电平时间) 进行匹配。
    因为我实验了几组空调红外编码方式进行对比，在改变MODE, TEMP,POWER, SWING，WIND SPEED的参数后，发现其第一byte数据是没有变化的，再加上HEADER(最少一个高电平+一个低电平 )差不多就算上9个bit。 然后和所有码库解码后的前9bit对比，和差值最小的那个做匹配。
   这个方式明显很烂，有投机取巧的感觉。而且空调的型号那么多，没办法一个一个全部测试。然后我就想到了第二个办法：👇
  **方案二**
  我把红外码库解码后的 时间(数组) 放到excel中->添加成折线图，观察其波形，发现可以根据其前导码，还有“0” “1"  电平高低的时间长度。根据这两个特征进行对比。但是仔细想了一下，发现还没有第一种方式靠谱呢 😄。 
   所以求助一下 有没有什么好的办法进行空调一键匹配呢？ 谢谢带佬

**Comment by strawmanbobi** [comment]
Hi，你好。
空调是状态码，确实不太容易匹配。如果硬要做的话，我给你一个参考的方法，你可以试试：
1. 先从离线码库，按照某一个固定状态，例如 temp=24，swing=on，speed=auto，mode=cool，加上 key=power，把所有的空调都解码出来，并且和 remote_index_id + brand_id 进行绑定转存到你的一个临时数据池内。
2. 要求用户在匹配的时候也把他们的遥控器切换到上面这个一摸一样的状态，你的接收装置收到之后，从刚才的数据池里，按照时间序列去比对，给予一定的容错差（例如 正负 200 微秒），然后逐个查询直到查到为止。

好像也只有这么一种方法了。
至于你的两个方法，好像都无法做到精确匹配。我的方法理论上是可行的，但是用户比较头大（因为他们需要把自己的遥控器校准到我们要求的状态）。

仅供参考吧，我自己也没想到什么比较好的解决方法，但是应该可以从这个思路上去优化这样。

但愿可以帮到你。

**Comment by Joketinnle** [comment]
NB嗷！ 非常感谢您的回答！！
