### ISSUE TITLE
没什么效果和用处

### ISSUE THREAD

**Issue by Liweiwei2Anna** [irext/irext#15]
家里的电视创维的，空调格力的，试了下，完全没反应啊 ， Android ， 有已经上线的例子吗？而不是简单的demo

**Comment by strawmanbobi** [comment]
不好意思，只有一个 demo，因为是开源项目。
不过呢，服务器前天过期了，阿里云给重启了下，我忘记了重新启动服务。
刚刚重启好了，你再试试。

**Comment by Liweiwei2Anna** [comment]
好的，晚上我回家再试试~
