### ISSUE TITLE
如何在orange pi上使用，并且实现本地化控制

### ISSUE THREAD

**Issue by zhuqiyun** [irext/irext#16]

**Comment by strawmanbobi** [comment]
您好，请具体描述希望使用的场景。譬如 orange pi 是否通过屏幕和用户交互，是否联网等等。
核心解码算法在任何具有 C runtime 的环境下都是可以编译执行的。据我所知， orange pi 承载的操作系统可以是 Android 也可以是 debian，这些都符合要求。只是不知道您具体希望部署的应用环境是怎样。
另外就是请详细查看 https://irext.net 的文档。文档内容能帮你解答大部分疑惑。
谢谢。

**Comment by strawmanbobi** [comment]
暂时关闭这个issue，如果后续还有问题，请另外开issue咨询，谢谢。
