### ISSUE TITLE
灯泡码库问题 - 小米app码库中有多个颜色按键，但是录码后网页中没有显示

### ISSUE THREAD

**Issue by sunguangqing** [irext/irext#17]
问题描述： 小米app码库中灯泡按键有红、绿、蓝、紫这些颜色键值，但是录取后网页中，color1、color2、 color3、color4等这些颜色值并没有变绿。不知是否应该对应这些颜色值变绿才对。
复现： 点击新增 --> 选择灯泡  -->  选择达伦灯泡第二个  -->  按键有红、绿、蓝、紫这些键值   -->  点击后打开网页查看录码对应结果。

**Comment by strawmanbobi** [comment]
才看到，过了好几个月了，改天看看。

**Comment by strawmanbobi** [comment]
这个是正常现象。参考 IRext 按键映射，灯里只有颜色 1，2，3，4... 没有具体的颜色，因为万能遥控我做不到同一个按键布局下映射给不同的灯的颜色。灯的话请暂时先跳过。后续会专门做针对灯做一些调整。
