### ISSUE TITLE
空调码离线解码问题

### ISSUE THREAD

**Issue by wudihuanx** [irext/irext#19]
您好，我从离线码库irda_new_ac_11272.bin解压空调开关机码，发现解压出来的关机码与遥控器一致，而开机码却比遥控器少了一截，因而设备不响应。直接采集遥控器的关机码有200个数据，开机码有300个数据；而码库解码出来开关机码都是200个数据；解码得到的开机码和遥控器开机码的前200个数据是对的上的，因此应该就是缺少了一段，而不是解码内容错误。
我是直接调用您提供的解码算法，在codeblocks里运行的，想向您请教一下debug的方向；
此外，我将code中的debug打印功能开启，发现AC parse中会提示有unsupported function id，这属于error吗？
`D:\UserSpace\WorkSpace\irext\irext\bin\Debug>irext.exe 0 irda_new_ac_11272.bin 0
Decode irda_new_ac_11272.bin as status-typed binary
tag(1).len = 9
tag(2).len = 7
tag(3).len = 8
tag(4).len = 7
tag(5).len = 3
tag(6).len = 1
tag(21).len = 20
tag(22).len = 14
tag(24).len = 66
tag(25).len = 40
tag(29).len = 104
tag(30).len = 198
tag(41).len = 4
tag(42).len = 4
tag(43).len = 6
tag(44).len = 1
tag(45).len = 6
tag(47).len = 1

unsupported function id : 33

unsupported function id : 40
AC parse done
Please input valid key code (Key code could be referenced from https://irext.net/doc#keymap) :
0
switch AC to power = 0, mode = 0, temp = 4, speed = 0, swing = 0 with function code = 8
ac status is not null in decode core : power = 0, mode = 0, temp = 4, wind_dir = 0, wind_speed = 0, keycode = 0, change_wind_direction = 0
key code = 0
4453,4453,539,1629,539,539,539,1629,539,1629,539,539,539,539,539,1629,539,539,539,539,539,1629,539,539,539,539,539,1629,539,1629,539,539,539,1629,539,1629,539,539,539,1629,539,1629,539,1629,539,1629,539,1629,539,1629,539,539,539,1629,539,539,539,539,539,539,539,539,539,539,539,539,539,539,539,539,539,1629,539,539,539,539,539,539,539,539,539,539,539,1629,539,1629,539,539,539,1629,539,1629,539,1629,539,1629,539,1629,539,5256,4453,4453,539,1629,539,539,539,1629,539,1629,539,539,539,539,539,1629,539,539,539,539,539,1629,539,539,539,539,539,1629,539,1629,539,539,539,1629,539,1629,539,539,539,1629,539,1629,539,1629,539,1629,539,1629,539,1629,539,539,539,1629,539,539,539,539,539,539,539,539,539,539,539,539,539,539,539,539,539,1629,539,539,539,539,539,539,539,539,539,539,539,1629,539,1629,539,539,539,1629,539,1629,539,1629,539,1629,539,1629,539,5256,
Please input valid key code :
99
ac binary close
IR Decode OK`

**Comment by strawmanbobi** [comment]
您好。
这里我理解是两个问题，分别解答。
1. irda_new_ac_11272.bin 这个文件我查了一下，对应的是码库里有许多的空调型号，所以不是很清楚你希望控制的空调是不是确认在这个范围之内。因为很多厂家的若干个不同空调的编码会设置得非常相似（比如格力空调，型号繁多，但是型号之间可能只有微小的按键差异）。所以产品设计的时候用户是需要在选定的品牌下逐一将遥控码枚举一遍进行匹配的。所以 debug 的方向应该是先从索引入手，比如你家空调是美的，先选美的，然后在美的下把所有码库都试一遍，如果能命中就OK，如果不命中，就说明码库没收录你指定的那一台，就需要扩充码库。
![ac_11272](https://user-images.githubusercontent.com/2515672/78205846-d17e7780-74cf-11ea-9dd8-8f684e872d2e.png)
    另外想请问下，你控制开机的时候是否已经将 ac_status.ac_power 设定成了开机状态，以及输入的 function （或者 key_number）设置成了“POWER“ 才能有效控制。

2. function_id 是有范围的，且和 key number 有一定映射关系，详细可以参考解码算法的 t_ac_function 枚举定义。

**Comment by wudihuanx** [comment]
您好，非常感谢拨冗帮忙解答！
1、请问采用11272编码的不同品牌的空调，它们的红外序列是完全一样的，不区分品牌信息吗？我理解红外码里应该会有品牌代码之类的信息，所以采用相同控制码的不同品牌的红外序列也会有差异的。但码库文件的解码过程中并不包含品牌参数；我的目标空调是美的的，我的匹配思路是将空调遥控器的关机码跟码库解压出来的关机码(状态信息一致)进行对比，以确认目标码库，这跟您给另外一位提问者提供的思路是一样的；我理解您的意思是，有可能我的空调对应码库文件并不是这一个，但凑巧它们的关机码相似度过高，导致匹配错误，是吧？这种情况我倒确实没有考虑到，那我再将美的的所有码库都匹配一遍看看。解压空调开/关机码的过程，是将初始状态先设定为关/开机(与目标相反)，然后再调用key_val=电源键来做的，这应该是没错的。
2、function_id确实是不应该大于7的，它与键值的对应关系我在代码里看到了。目前我主要是在试电源码，所以key_code=0, 对应function_id=1，而如上面贴出的debug信息，在解码过程中出现这些“unsupported function id”的提示，是解码算法运行出错呢，还是说因为码库高压缩比下的一种正常无效跳转呢。想请您帮忙确认一下。我比较倾向第二种可能。
再次感谢！

**Comment by strawmanbobi** [comment]
1. "有可能我的空调对应码库文件并不是这一个，但凑巧它们的关机码相似度过高，导致匹配错误，是吧？"  -- 对，就是这个意思。但是红外码里并不含有品牌和电器型号的信息，它们仅仅是一些控制指令。如果想知道品牌和型号对应哪些码库，请参考索引部分的逻辑。而且 IRext 库（事实上市面上几乎所有的库）都不包含具体型号，所以当前都是按照同一品牌逐一匹配的方式精确锁定你的电器对应的某一个码库文件。
2. 应该是你输入了不正确的 key number 值导致的吧。你再检查一下代码。

**Comment by wudihuanx** [comment]
您好，关于问题2；确认与key number无关，因为它是在ac_parse阶段出现的，此时还未用到key code；定位了一下，是在函数parse_function_1()里面报错的，我将相关信息打印出来：

`function_1 tag data :
3039 3036 3032 4436 3033 3239 3034 3037 3035 4638 3044 3038 3030 4144 3031 3532 3032 4146 3033 3530 3034 3435 3035 4241 3044 3232 3030 4144 3031 3532 3032 4146 3033 3530 3034 4135 3035 3541 3044 3239 3030 4144 3031 3532 3032 4146 3033 3530 3034 4335 3035 3341
function_1 hex data :
0906 02d6 0329 0407 05f8 0d08 00ad 0152 02af 0350 0445 05ba 0d22 00ad 0152 02af 0350 04a5 055a 0d29 00ad 0152 02af 0350 04c5 053a
unsupported function id : 33, in parse function_1

unsupported function id : 40, in parse function_1`

其中，tag data就是码库文件内的原始数据，在文件内的地址是[0x0EA,0x151]，核对无误；
hex data则是string2hex转换后的结果，也OK；
那么根据函数parse_function_1()的结构，hex data的首byte是seg_len，第二个byte-1是function_id，其余则是seg_data。则这段hex data里包含4个segment，长度分别为09/0d/0d/0d，而function_id分别为(06-1)/(08-1)/(22-1)/(29-1)，那这后两个id就是unsuppor id：33 and 30；

到此为止，看起来parse 过程似乎没有出错，因为四段seg_len与总长度是吻合，应该没那么巧parse出错后这个长度也能对的上；

以上，请帮忙看一下呢。
谢谢！

**Comment by strawmanbobi** [comment]
我把 print enable 看了下，这个 unsupprted function id 应该是之前录入码库的时候，录入了一些预先设计当中的功能，比如横扫风向，定时关闭等，但是最后算法里面并没有支持的。
可以暂时忽略，另外如果你想深入探究空调算法的话，可以给我一个邮箱，我把空调编码相关的资料发给你。

**Comment by wudihuanx** [comment]
您好，非常感谢您的解答和帮助；
我的邮箱是2698126082@qq.com；
谢谢！

**Comment by strawmanbobi** [comment]
另外请问下您是个人开发者还是企业用户？我这边需要了解一下，可以加我微信沟通。
