### ISSUE TITLE
请问有Arduino版本了么？

### ISSUE THREAD

**Issue by HartleyLau** [irext/irext#2]
刚刚了解到这个库，感觉挺棒的，不知道是否已经发布Arduino版本？

**Comment by strawmanbobi** [comment]
Hi，您好。目前我没有功夫特意去写 Arduino 的版本，但是这个库的其中一个用户已经尝试过在 ESP 上调试过了，完全是C语言无缝移植的，所以理论上移植会很平滑，您可以试试。
详细情况欢迎加我微信聊啊~
