### ISSUE TITLE
关于功能问题

### ISSUE THREAD

**Issue by waqq1314** [irext/irext#20]
我之前没注意到有现成android demo，我就自己根据c的代码通过jni方式实现了功能，但是发现很多功能都不行（空调）。比如我就选奥克斯空调的第一个码库（new_ac_9377）,发现温度减不行，但是温度加正常，然后换一个码库测试也依旧。
然后我继续查阅文档，发现了现成的Android demo，通过测试发现也有这个问题。
这是为啥

**Comment by strawmanbobi** [comment]
能不能告诉我你在发送温度减时的具体参数，ac status 以及 key code

**Comment by waqq1314** [comment]
针对app demo，功能上我什么都没动，仅仅在ControlFragment.java的onClick方法后面加上了下面代码

`if (decoded!=null)
            Log.e("decode",decoded.length+"");`

打印出来的结果有三种情况，一是根本就没出来，即没解出数据，二是显示长度为0，按温度减就是这个现象，三是有正常长度值，比如温度+，开关等

**Comment by strawmanbobi** [comment]
get 到了。这是 example 的 bug（0.2.4 升级了算法之后 example 忘记了改)，是这样的：
最新的解码算法 0.2.4 之后（目前是 0.2.5）明确了用户输入的按键编号，你参考 irext/core 的解码算法代码，空调能识别的按键码为：
![image](https://user-images.githubusercontent.com/2515672/80063426-7a1c7600-8568-11ea-8b64-1099d341e939.png)
在 example 当中按下温度 - 时，发出的按键编号为：
![image](https://user-images.githubusercontent.com/2515672/80063521-a932e780-8568-11ea-97f7-e451d2981bc4.png)
这个 Constants.ACFunction.FUNCTION_TEMPERATURE_DOWN.getValue(); 值为 4，所以算法只能返回空。
近期我修改一下 example 吧，根据文档里的安全编号对齐下。
你也可以帮我改，然后给我一个 PR，:rofl:

**Comment by waqq1314** [comment]
ok，可以了，改动了这个地方的值
![image](https://user-images.githubusercontent.com/9473678/80069059-4561ec00-8573-11ea-99c5-d2c37e310103.png)
其他地方没改动吧？我用之前的c代码解码还能行吗？我做的那个app也只是公司的demo，如果按照你目前的demo去弄的话又要改动很多东西，所以问一下之前的c库有没有改动什么？另外我用的是离线解码方式

**Comment by strawmanbobi** [comment]
0.2.4 和 0.2.5 改了按键映射，如果你之前的代码逻辑是正常的，就可以不改了。不过个人还是建议都统一到最新的版本上来（工作量请自己评估），方便将来维护。码库都没修改，还是和原来一样。
PS：照你这么说将来如果我核心算法升级了你还是得升级啊。

**Comment by strawmanbobi** [comment]
Android example 已经更新，关闭此贴。
