### ISSUE TITLE
[IRIS]<IRext Code Collector>shows nothing

### ISSUE THREAD

**Issue by Joketinnle** [irext/irext#21]
Open <IRext Code Collector> App and Universal Remote App in VirtualBox , then press remote button IRext Code Collector didnt show the message. ;p

**Comment by strawmanbobi** [comment]
确实是个 bug，近期抽空 fix。谢谢。

**Comment by Joketinnle** [comment]
> 确实是个 bug，近期抽空 fix。谢谢。

谢谢 好人一生平安😘

**Comment by strawmanbobi** [comment]
已经修好。不过要麻烦重新下载虚拟机：
http://irext-lib-release.oss-cn-hangzhou.aliyuncs.com/IRIS_CC/IRIS-CC_20200428.tar.gz
