### ISSUE TITLE
[IRIS] There are 2 <menu> button in projector console. 

### ISSUE THREAD

**Issue by Joketinnle** [irext/irext#22]
[https://irext.net/iris/](url)
**IRIS** -> Console -> Cates: PROJECTOR -> Brand: Sony ->Detail 
There are 2 menu buttons one of which should be the mute button?

**Comment by strawmanbobi** [comment]
昨天看你截图以为是 TV 里面出了两个 menu button。
projector 出两个 menu button 是正常的... 因为按键映射里就是这样，但是你可以只录入一个，另一个置空就好了。
参见：http://irext.net/doc/  按键映射。

**Comment by Joketinnle** [comment]
😂
