### ISSUE TITLE
电视码库问题

### ISSUE THREAD

**Issue by sunguangqing** [irext/irext#23]
问题描述： 小米app码库中新增一个电视品牌后，点击录的第一个码在网页中不会显示出来，网页中显示的是未录状态，点击别的按键再次去点击第一个录的码，再去网页中看就会是绿色。
复现： 点击新增 --> 选择电视 --> 选择任意一个电视品牌 --> 录几个按键 --> 点击后打开网页查看第一个录的按键  --> 返回app再次点击第一个录的按键  -->  去网页查看。

**Comment by strawmanbobi** [comment]
是个bug，已经修复后台。无需更新虚拟机。
