### ISSUE TITLE
码库排重问题

### ISSUE THREAD

**Issue by sunguangqing** [irext/irext#24]
问题描述： 新增一个新电视品牌，网页中点击检测重复，提示重复检测失败。
复现： 胜利电视码库第六个第七个和万利达电视码库第一个。 正确检测重复可以见乐视电视码库第一个。

**Comment by strawmanbobi** [comment]
是在排重过程中新建品牌的 operator 字段为空引起的 null pointer exception，已经解决并更新，谢谢。
