### ISSUE TITLE
风扇是否存在关键词匹配不正确

### ISSUE THREAD

**Issue by sunguangqing** [irext/irext#25]
app码库中shake_wind是否是网页中的Shake
风扇码库一直都很少按键绿色，不知道是本来就缺码还是有关键词匹配错了导致的。帮忙看下~

**Comment by strawmanbobi** [comment]
shake_wind 应该就是 Shake（摇头）
另外近期会试图优化一下风扇的按键映射。谢谢指出。

**Comment by strawmanbobi** [comment]
解决摇头映射问题。
风速映射想想还是算了，改动太大，暂且保留。
