### ISSUE TITLE
机顶盒input按键映射问题

### ISSUE THREAD

**Issue by sunguangqing** [irext/irext#26]
app中机顶盒input按键映射是“输入法”，但是点击了之后，网页上面没有相应的变绿。之前录的时候是好的是会变绿的，上次修复“上页”和“下页”之后，input才出现的问题。

**Comment by strawmanbobi** [comment]
这个匹配不到是正常的，因为 input 本意为 ”输入源“ 不是所有机顶盒都有。
你这个是 “输入法”，从后台日志看文本全文是 input method，如图。
![image](https://user-images.githubusercontent.com/2515672/83416885-ecc81d80-a453-11ea-9bc7-da0b47b45cdf.png)
