### ISSUE TITLE
机顶盒新增已有品牌码库，网页中不显示，但是新增不存在品牌会显示

### ISSUE THREAD

**Issue by sunguangqing** [irext/irext#27]
app中新增网页中已经有的品牌码库，刷新网页，该品牌码库显示“No matching records found”。
app中新增网页中不存在的品牌码库，刷新网页，点击眼睛，码库正常显示。

**Comment by strawmanbobi** [comment]
这个 issue 也不是一个 bug。你应该这么理解，以 ”歌华“ 为例：
1. IRext 的存量码库里是有名为 ”歌华有线“ 的运营商旗下的机顶盒的，这个在 IRIS 面板里看不到，但是在 IRext 面板里能看到（注意 IRext 是 IRIS 的不同）。
2. 录码进去的是 ”歌华有线通用“ 运营商下的机顶盒，从文字上无法和现存的 "歌华有线” 匹配，所以被 IRIS 认为是新的运营商，而实际上它和存量的 “歌华有线” 是同一个运营商。
3. 在新增的时候，你可以选择合并，即将 IRIS 录入进来的 “歌华有线通用” 和存量的 ”歌华有线“ 合并，合并之后所有的 “歌华有线通用” 机顶盒会自动归并到 “歌华有线” 下，并且在之后再录入 "歌华有线通用” 旗下机顶盒的时候也会自动归属到 “歌华有线” 运营商下。以存量为准。
![image](https://user-images.githubusercontent.com/2515672/83417774-23eafe80-a455-11ea-8cab-87c21e55edcf.png)
