### ISSUE TITLE
app新增飞利浦电视，网页中看不到

### ISSUE THREAD

**Issue by sunguangqing** [irext/irext#28]
app中新增飞利浦电视，网页中不显示。

**Comment by strawmanbobi** [comment]
遗留问题，之前有一个版本有bug的时候，录入的飞利浦电视机错误的加入了风扇品类下，导致现在再录报“已存在”错误，实际上是品类错误。已修复数据。
同时看了下其它可能的错误品类，只有飞利浦一个case。
