### ISSUE TITLE
空调温度加减问题

### ISSUE THREAD

**Issue by waqq1314** [irext/irext#29]
公司的空调，目前找对应的码库，发现有几个码库的开关功能都有用，模式行不行未知（因为看不到，只能听见响声）。
然后测试温度加减功能，因为这个可以直接看到。于是就发现问题了，只要处于空调开的状态，温度加减功能始终得不到数据，返回长度一直是0，相反设置电源为关闭状态却有数据，但是发送给空调却是关机

**Comment by strawmanbobi** [comment]
您好，请问你给的参数是什么？包括 ac_status 以及 key_code。

**Comment by waqq1314** [comment]
后来正好发现是ac_status没初始化造成的

**Comment by strawmanbobi** [comment]
那么请问你们修改之后能正常控制了吗？

**Comment by waqq1314** [comment]
可以了呀，能看到温度变化，但模式因为没指示所以不知道，应该也没问题。

**Comment by strawmanbobi** [comment]
好的，多阅读文档，多测试。有任何问题均可 github issue 讨论。
