### ISSUE TITLE
NEC投影仪命名为1不显示

### ISSUE THREAD

**Issue by sunguangqing** [irext/irext#31]
复现：新增NEC投影仪第一个，命名为NEC投影仪1，刷新网页不出现；命名为NEC投影仪3，刷新页面会出现。

**Comment by strawmanbobi** [comment]
才看到，过了好几个月了...

**Comment by strawmanbobi** [comment]
因为数据库里已经有 NEC 投影仪 1 了，是别人录的，所以你看不到。这个可以跳过。
