### ISSUE TITLE
IRIS 英文网页中不存在 IRIS-CC 下载链接

### ISSUE THREAD

**Issue by Caffreyfans** [irext/irext#33]
网页根据系统设定语言而显示，无法手动选择网页显示语言。IRIS-CC 下载链接中文网页中存在，英文版中不存在。

**Comment by strawmanbobi** [comment]
多谢反馈，我今天看看。
话说你怎么在用英文版浏览器？装B么？哈哈。

**Comment by strawmanbobi** [comment]
已更新。谢谢发现问题。
