### ISSUE TITLE
机顶盒创建SP

### ISSUE THREAD

**Issue by sunguangqing** [irext/irext#34]
复现1： 例如沁源广电机顶盒不存在已有SP，新建SP后，刷新机顶盒，点击眼睛沁源广电机顶盒还能看见；而长治广电机顶盒存在已有SP，选择合并，刷新机顶盒，点击眼睛长治广电机顶盒消失不见。
问题2： 晋中有线机顶盒分为晋中有线·昔阳、晋中有线·太谷，不知是新建两种SP，还是两个都合并到已有的晋中有线SP下。

**Comment by strawmanbobi** [comment]
问题2：先合并到晋中有线下面。
问题1的第二个小问题：长治机顶盒合并之后在眼睛（确切说应该叫新发现的项目）当中看不见属于正常行为。因为在非眼睛（已知项目）列表里看到它了。如下图。
![image](https://user-images.githubusercontent.com/2515672/90134834-5c3b8100-dda4-11ea-8bb3-fdda19cc1a35.png)

**Comment by strawmanbobi** [comment]
问题1的第一个小问题我再看看，多谢提出。

**Comment by strawmanbobi** [comment]
问题1我操作了一把，可以创建到已知项目列表啊。为什么你不行？如图：
![image](https://user-images.githubusercontent.com/2515672/90135074-b0defc00-dda4-11ea-8073-4882215afc9f.png)

**Comment by strawmanbobi** [comment]
此 bug 暂不结案，待观察...

**Comment by sunguangqing** [comment]
阳城广电新增SP之后，未知列表状态应该是看不见了的，现在未知列表还能看见；已知列表现在已经存在了，但是已知列表下面应该是有码库列表显示，但是显示是空。

**Comment by strawmanbobi** [comment]
好像是页面刷新的问题：
1. 新增 SP 实际上是成功的，新增之后在未知列表里显示了已知列表的数据；
2. 切回已知列表的时候第一时间刷新失败了，你切换到另一个 SP，再切回来就有了。
应该都是前端问题。

**Comment by strawmanbobi** [comment]
已经解决：
1. 新增 SP 之后自动跳回已知 SP 页面。
2. 解决已知 SP 页面首次无法刷新特定 SP 下已经录入的 index 的问题。
请后续注意观察问题是否解决。
