### ISSUE TITLE
下载码库二进制文件失败

### ISSUE THREAD

**Issue by i402097836** [irext/irext#35]
在调用获取二进制文件请求后，接口请求成功（code:0）,但是entiy一直没有数据，请问可能是什么原因？
http请求返回的结果如下：{"status":{"code":0,"cause":"success"},"entity":null}

**Comment by Caffreyfans** [comment]
调用成功后，你应该接收流哦。不是以文本的形式返回了。

**Comment by strawmanbobi** [comment]
下载接口是返回 input stream，是一个 octet content-type 的二进制。
再试试。

**Comment by i402097836** [comment]
我用的是老板的服务，调用的是/irext/open接口，看代码entry里应该返回的是sessionId，拿到sessionID去打开二进制文件， 但是现在调用接口成功，sessionId为空

**Comment by Caffreyfans** [comment]
> 我用的是老板的服务，调用的是/irext/open接口，看代码entry里应该返回的是sessionId，拿到sessionID去打开二进制文件， 但是现在调用接口成功，sessionId为空

你是在用在线解码吗？

**Comment by strawmanbobi** [comment]
现在已经没有 open 这个接口了，文档更新了，请麻烦看下最新的用法。如果你们使用的是离线服务，可以考虑升级下数据和离线服务容器。

**Comment by strawmanbobi** [comment]
请问下使用了更新的接口能帮助你解决问题么？

**Comment by i402097836** [comment]
> 
> 
> 请问下使用了更新的接口能帮助你解决问题么？

没有更新接口，因为我们在本地部署了一套服务，全部升级到新版需要时间，就没有升级，问题应该出在我们这边，但是有一点没明白，遥控码索引对象 (RemoteIndex)中status字段标识是否有效(1: 有效， 0: 无效)，默认为1，但是查看数据库有很多状态为2,4,5的，请问这个代表什么状态？这种状态的下的码库可以用吗？

**Comment by strawmanbobi** [comment]
您好，不可以用。这个状态值和你们对码库进行自行录入和质量管理有关，解释如下：
    ITEM_INVALID = 0;  // 不可用，表示这个码库被标记删除了。
    ITEM_VALID = 1; // 能正常解码且确实能控制的已发布的码。
    ITEM_VERIFY = 2; // 码库管理当中已经录入，等待验证的码。
    ITEM_PASS = 3; // 码库管理当中已经验证通过但未发布的码，理论上这种也能用。
    ITEM_FAILED = 4; // 码库管理当中已经录入，但是验证失败的码（解码失败或者解码出来不能实际控制电器） 。
    ITEM_UNDETERMINED = 5; // 这种一般是重复码，未决状态，理论上可用，但是一般不用。

**Comment by strawmanbobi** [comment]
另外如果能迁移到新的服务，尽量迁移吧，改进了不少 bug，而且现在支持容器化部署，升级起来是非常方便的。
当然如果你们对服务端进行了定制化开发，酌情处理吧。谢谢。

**Comment by i402097836** [comment]
> 
> 
> 另外如果能迁移到新的服务，尽量迁移吧，改进了不少 bug，而且现在支持容器化部署，升级起来是非常方便的。
> 当然如果你们对服务端进行了定制化开发，酌情处理吧。谢谢。

好的，多谢了。
