### ISSUE TITLE
机顶盒创建SP，修改默认SP名称后，提示创建成功，但是实际并没有

### ISSUE THREAD

**Issue by sunguangqing** [irext/irext#36]
复现：  辽宁省-锦州市-北方广电·义县机顶盒，选择创建SP-不选择合并-修改SP名称（北方广电·义县 --> 北方广电）-点击确认创建，提示创建成功，但是刷新后并没有创建成功。重复3-5次依旧如此

**Comment by strawmanbobi** [comment]
新录入的机顶盒在数据表中只有 "名称“ 和 city_code 字段。如果新增运营商并且修改名称的话，之前的版本会用新的名称去匹配码库表的机顶盒条目，于是匹配不到，所以其实运营商创建成功了，但是那些机顶盒的条目并没有归结到新增运营商名下，所以在新增列表中仍然可见。
已修改。
**但是可能有一个逻辑是无法逾越的，那就是例如 北方广电.义县 这个运营商改名 ”北方广电“ 之后，已经录入的北方广电.义县机顶盒是可以归结到新的 ”北方广电“ （此处应该是辽宁省锦州市）之下。然而继续新增 “北方广电.义县“ 机顶盒仍会被视为有一个全新的 ”北方广电.义县“ 的运营商产生。这种情况下还需尽可能判断，将这个带有新名字的运营商下的机顶盒完全录入之后，再通过隐藏列表创建运营商。**

**Comment by sunguangqing** [comment]
说其实运营商创建成功了，但是我在“可能会合并的SP”列表下应该能找到创建成功的SP啊，但实际确找不到创建成功的“北方广电”，因为“北方广电·义县”和“北方广电·锦州”我都是要分类的“北方广电”这个SP下的。
