### ISSUE TITLE
IRext 登录问题

### ISSUE THREAD

**Issue by sunguangqing** [irext/irext#37]
IRext 页面点击登入，输入账号和密码后状态没有改变。

**Comment by Caffreyfans** [comment]
可能是密码错误，如果是密码错误建议点忘记密码重新配置下密码。注意在邮件中激活密码就好了。

**Comment by strawmanbobi** [comment]
登录这一版修大改了，改出bug来了...

**Comment by strawmanbobi** [comment]
已修复。redis 的 key 弄错了。失敬~ 💯
