### ISSUE TITLE
空调温度设置

### ISSUE THREAD

**Issue by clanaid** [irext/irext#6]
空调控制某一温度解码时，keyCode是要传什么值，应该不是增加/减小温度吧

**Comment by strawmanbobi** [comment]
传增加、减少温度即可。
但是 ac_status 里的 temperature 值要设置对。
原理是，空调（除关机指令外）不仅受到 ac_status 的作用，还同时受到 key_code 的作用，举个例子：
”从 制热 28 度切换到 制冷 28度“ 所发出的指令 和 ”从制冷 27度切换到制冷 28度” 所发出的指令是不同的。

**Comment by clanaid** [comment]
ac_status 其他的状态不变，例如只增加温度值，那keyCode传入加、减少温度转出来的码控制就是一直增加温度吗？还是说要增加温度时传增加，减少温度时传入减少才是正确的

**Comment by clanaid** [comment]
对了，请问下空调的红外码都是一对高低电平表示一个码？
逻辑1是否以500us载波+1500us无载波时间
逻辑0以500us载波+500us无载波时间

**Comment by strawmanbobi** [comment]
你的第一个问题：关于空调状态切换，空调属于状态码，是你发什么状态去，它就切换成什么状态，keyCode是辅助生成这个状态码的迁移量，可以理解一下解码算法里的 function code 的处理过程。
第二个问题：是的，确切的说，红外码一定要以一组 有载波/无载波 的模拟信号作为一个数字逻辑信号 1 或者 0， 但是载波和无载波持续时间并不都是 500/1500 以及 500/500，具体要看协议。500/1500 以及 500/500 属于 udp6121 系列协议，也就是常说的 NEC码。当然还有其它的许多协议，IRext 里总共收录了 200 多个协议。

**Comment by clanaid** [comment]
嗯，我看接口返回空调的协议都是new_ac 是否代表都是统一协议的？

**Comment by strawmanbobi** [comment]
状态码编码方式和命令码完全不同，所以空调里不是由协议来编码的，具体可以理解下 decode 和 encode 核心算法代码。后续这部分到一定时机我也会放出来编解码的文档。

**Comment by clanaid** [comment]
好的，还有个问题请问下，ACFunction里的FUNCTION_SWITCH_SWING 和 FUNCTION_SWITCH_WIND_DIR都是风向控制吗

**Comment by strawmanbobi** [comment]
FUNCTION_SWITCH_SWING 是控制空调在自动摆风和固定风之间切换
FUNCTION_SWITCH_WIND_DIR 是切换固定风的送风角度
decode 接口里有个参数叫 change_wind_dir，如果是 1 的话，那么表示这次 swing switch 的同时还要切换固定风的角度，否则就只是在摆风和固定风之间切换状态。

**Comment by strawmanbobi** [comment]
多拉点小伙伴来点赞啊。

**Comment by clanaid** [comment]
上次有事就耽搁没看了，change_wind_dir参数范围是多少？

**Comment by strawmanbobi** [comment]
请自己阅读代码，完全可以理解。既然开源就是让你读代码的。

**Comment by strawmanbobi** [comment]
而且你问的几个问题，在网站文档上都有，这里就不一一作答了，请仔细阅读网站文档上的解码 API 章节。

**Comment by clanaid** [comment]
嗯好的，我也有在阅读android的example源码，只是在这里有了点疑惑请教下

**Comment by strawmanbobi** [comment]
好的，可以扫码加我微信，方便沟通。

**Comment by clanaid** [comment]
ok，不过我看到ReadMe那里的微信二维码图片失效了，挂了。
是不是应该这样理解，
在FUNCTION_SWITCH_SWING 下，change_wind_dir参数应该传入0，ACStatus中acWindDir的值只有0和1两种状态代表开启自动摆风和停止自动摆风（固定风）
在FUNCTION_SWITCH_WIND_DIR下，change_wind_dir参数应该传入1，同时根据getAcSupportWindDirection返回的值知道固定风档位，ACStatus中acWindDir的值范围是0-（WindDirection - 1）

**Comment by strawmanbobi** [comment]
对
