### ISSUE TITLE
关于ESP8266接收时长序列的方式请教

### ISSUE THREAD

**Issue by CherishAYH** [irext/irext#7]
大佬您好，我准备做的项目是：手机APP解码→MQTT通过JSON传送时间序列到ESP8266→8266根据收到的数据发射红外信号。
我程序写到ESP8266接收数据进行处理这一步了（现程序可以根据时长数组控制红外发射了，已成功发射一个信号控制空调）。
不过现在有个问题困扰了了我好几天了，问题点如下:ESP8266接收到的MQTT消息需要使用cjson进行解析，但是红外信号时长序列数组有长有短，比如NEC协议才67个时长序列数据，格力空调的红外时长序列数组有200+个时长序列数组，我知道两种解决方案：

1. 将数组的长度定为目前已存在的信号的最长长度比如定义时长序列数组长度为400，但是这样好像太占内存了；
2. 用malloc函数定义动态数组，数组用完之后再调用free释放内存，但问题是没用过这种方式，不知道在mqtt消息回调函数中执行该函数行不行。

还请大佬指点一二。

**Comment by strawmanbobi** [comment]
这个根据你的实际情况来。一般嵌入式系统里如果有全局空间，就尽量使用全局空间。也就是定义一个 400 字节的全局变量来存放这个序列。不推荐用 malloc 堆（耗CPU），或者局部变量（可能会栈溢出）。

**Comment by CherishAYH** [comment]
> 这个根据你的实际情况来。一般嵌入式系统里如果有全局空间，就尽量使用全局空间。也就是定义一个 400 字节的全局变量来存放这个序列。不推荐用 malloc 堆（耗CPU），或者局部变量（可能会栈溢出）。

多谢大佬指点，作为小白的我又学到了一些新知识。ESP8266好像空间挺大的可以定义出一个这么大的数组，但是另一个问题又来了，您的irext红外库中目前最长的时间序列是多少啊？这个数据能查得到吗？到底是300、400、500还是600呢？

**Comment by strawmanbobi** [comment]
参考 https://github.com/irext/core/blob/master/src/ir_decoder/include/ir_defs.h
#define USER_DATA_SIZE 1636
