### ISSUE TITLE
下载列表中 remoteMap 值与实际下载接口值不一致

### ISSUE THREAD

**Issue by Caffreyfans** [irext/irext#9]
例如当我获得一个 **remoteMap** 数据是:
```
{'id': 3480, 'categoryId': 1, 'brandId': 2, 'protocol': 'new_ac', 'remote': '5227', 'remoteMap': 'new_ac_5227', 'status': 1, 'subCate': 1, 'priority': 45, 'binaryMd5': '2a1afce6a3223fa0e3c871aec95e360f', 'updateTime': '2016-11-27 11:00:00'}
```
当我使用数据中的 **remoteMap** 的值去 **OSS** 下载时发现并不能下载，查看 **database** 中 **irext-binaries** 中的文件也没有找到与该 **remoteMap** 值相匹配的文件，而只有个与该值接近且带有前缀 **irda_** 的文件。

**Comment by strawmanbobi** [comment]
Dear，
目前推荐用 OSS 的下载链接，方法如下：
http://irext-debug.oss-cn-hangzhou.aliyuncs.com/irda_<remote_map>.bin
例如你上面的例子里应该是：
http://irext-debug.oss-cn-hangzhou.aliyuncs.com/irda_new_ac_5227.bin
